# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'ZhongHuiNong' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for ZhongHuiNong
    
    # Network
    pod 'Moya/RxSwift'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'SwiftyJSON'
    pod 'ReachabilitySwift'
    
    
    # Rx
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'NSObject+Rx'
    
    # UI
    pod 'SnapKit'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'JXCategoryView'
    pod 'PPBadgeViewSwift'
    pod 'TYCyclePagerView'
    pod 'EmptyDataSet-Swift'
    
    # Tools
    pod 'Then'
    pod 'Cache'
    pod 'EZUIKit' # 萤石开放平台OpenSDK封装的UI组件, 直播流播放，视频监控
    pod 'WechatOpenSDK'
    pod 'RTRootNavigationController'
    
     
    target 'ZhongHuiNongTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'ZhongHuiNongUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
